### ISSUE TITLE
Command Filtering - Off by default

### ISSUE THREAD

**Issue by willaien** [formlesstree4/HunieBot2#2]
IMO, Command Filtering, while necessary for some modules, is rather obtuse to the uninitiated.

It's a bit non-intuitive that you have to run .set_command_permissions on each command you've added to your bot.

It should be off by default, and added as a property to the HandleCommandAttribute, so you can do something like:
`[HandleCommand(CommandEvent.CommandReceived | CommandEvent.AnyMessageReceived, UserPermissions.User, "roll", IsFiltered = true)]`
to opt-in to filtering.

**Comment by formlesstree4** [comment]
Considering I currently do [horrible things](https://github.com/formlesstree4/HunieBot2/blob/master/HunieBot.Host/Injection/Implementations/Permissions/HunieCommandPermissions.cs#L20) to work around the fact commands must have permissions associated with them, I like this enhancement request.

It'll probably make it in before #1 does simply because this is a relatively easy win.

**Comment by formlesstree4** [comment]
Committed fix.
